version: 0.0
os: linux

files:
  - source: /app.py              # Source in GitHub repo
    destination: /var/www/app/    # Destination on EC2 instance

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
